import type { Team } from '../types/api';

const FIFA_TO_FLAG: Record<string, string> = {
  ALB: 'al',
  ALG: 'dz',
  ANG: 'ao',
  AUS: 'au',
  AUT: 'at',
  AZE: 'az',
  BEL: 'be',
  BEN: 'bj',
  BFA: 'bf',
  BIH: 'ba',
  BLR: 'by',
  BOL: 'bo',
  BRA: 'br',
  BUL: 'bg',
  CAN: 'ca',
  CMR: 'cm',
  CHI: 'cl',
  CHN: 'cn',
  CIV: 'ci',
  COL: 'co',
  CPV: 'cv',
  CRC: 'cr',
  CRO: 'hr',
  CUB: 'cu',
  CZE: 'cz',
  DEN: 'dk',
  ECU: 'ec',
  EGY: 'eg',
  ENG: 'gb-eng',
  ESP: 'es',
  EST: 'ee',
  FIN: 'fi',
  FRA: 'fr',
  GEO: 'ge',
  GER: 'de',
  GHA: 'gh',
  GRE: 'gr',
  GUA: 'gt',
  HON: 'hn',
  HUN: 'hu',
  IRL: 'ie',
  IRN: 'ir',
  ISL: 'is',
  ISR: 'il',
  ITA: 'it',
  JPN: 'jp',
  KOR: 'kr',
  KSA: 'sa',
  MAR: 'ma',
  MEX: 'mx',
  NGA: 'ng',
  NED: 'nl',
  NOR: 'no',
  NZL: 'nz',
  PAN: 'pa',
  PAR: 'py',
  PER: 'pe',
  POL: 'pl',
  POR: 'pt',
  QAT: 'qa',
  ROU: 'ro',
  RUS: 'ru',
  SCO: 'gb-sct',
  SEN: 'sn',
  SRB: 'rs',
  SUI: 'ch',
  SWE: 'se',
  TUN: 'tn',
  TUR: 'tr',
  UKR: 'ua',
  URU: 'uy',
  USA: 'us',
  VEN: 've',
  WAL: 'gb-wls',
  ZAM: 'zm',
  ZIM: 'zw',
  ARG: 'ar',
};

export const getFlagCode = (team: Team) => {
  const code = team.tla?.toUpperCase();
  if (code && FIFA_TO_FLAG[code]) return FIFA_TO_FLAG[code];
  return null;
};
